version: '3.4'

services:
  exercise.wwwapi:
    image: ${DOCKER_REGISTRY-}exercisewwwapi
    build:
      context: .
      dockerfile: exercise.wwwapi/Dockerfile
    ports:
    - "7000:7000"
    - "7001:7001"
    networks:
    - "gwd-network"
    depends_on:
      workshop.database:
        condition: service_healthy
  workshop.database:
    container_name: 'workshop.database'
    image:  postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - './.containers/students-data:/var/lib/postgresql/data'
    ports:
    - 5432:5432
    networks:
    - gwd-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
networks:
  gwd-network:
    driver: bridge